In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv('./Data science with Python 1/movies.dat',sep="::",names=["MovieID","Title","Genres"])

C:\Users\ADHIRAJ MAJUMDAR\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

In [3]:
movies.head()

   MovieID                               Title                        Genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy

In [4]:
ratings = pd.read_csv('./Data science with Python 1/Ratings.dat',sep="::",names=["UserID","MovieID","Rating","Timestamp"])

C:\Users\ADHIRAJ MAJUMDAR\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

In [5]:
ratings.head()

   UserID  MovieID  Rating  Timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

In [6]:
users = pd.read_csv('./Data science with Python 1/Users.dat',sep="::",names=["UserID","Gender","Age","Occupation","Zip-code"])

C:\Users\ADHIRAJ MAJUMDAR\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

In [7]:
users.head()

   UserID Gender  Age  Occupation Zip-code
0       1      F    1          10    48067
1       2      M   56          16    70072
2       3      M   25          15    55117
3       4      M   45           7    02460
4       5      M   25          20    55455

In [18]:
len(movies["MovieID"].unique().tolist())

3883

In [16]:
len(ratings["MovieID"].unique().tolist())

3706

In [21]:
user_ratings = pd.merge(users,ratings,how="inner",on="UserID")

In [22]:
user_ratings.head()

   UserID Gender  Age  Occupation Zip-code  MovieID  Rating  Timestamp
0       1      F    1          10    48067     1193       5  978300760
1       1      F    1          10    48067      661       3  978302109
2       1      F    1          10    48067      914       3  978301968
3       1      F    1          10    48067     3408       4  978300275
4       1      F    1          10    48067     2355       5  978824291

In [23]:
user_ratings.shape

(1000209, 8)

In [24]:
Master_Data = user_ratings.merge(movies,how="inner",on="MovieID")

In [25]:
Master_Data.head()

,UserID,Gender,Age,Occupation,Zip-code,MovieID,Rating,Timestamp,Title,Genres
0,1,F,1,10,48067,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama
1,2,M,56,16,70072,1193,5,978298413,One Flew Over the Cuckoo's Nest (1975),Drama
2,12,M,25,12,32793,1193,4,978220179,One Flew Over the Cuckoo's Nest (1975),Drama
3,15,M,25,7,22903,1193,4,978199279,One Flew Over the Cuckoo's Nest (1975),Drama
4,17,M,50,1,95350,1193,5,978158471,One Flew Over the Cuckoo's Nest (1975),Drama

In [26]:
Master_Data[Master_Data["Title"].str.contains("Toy Story")]["Rating"].tolist()

[5,
 4,
 4,
 5,
 5,
 4,
 5,
 3,
 4,
 3,
 3,
 5,
 5,
 5,
 5,
 4,
 4,
 5,
 5,
 5,
 4,
 5,
 3,
 3,
 5,
 5,
 4,
 3,
 3,
 4,
 4,
 3,
 4,
 5,
 3,
 3,
 3,
 5,
 5,
 3,
 3,
 5,
 4,
 2,
 4,
 4,
 5,
 4,
 5,
 3,
 4,
 2,
 4,
 5,
 5,
 5,
 4,
 4,
 5,
 4,
 4,
 2,
 5,
 5,
 5,
 4,
 3,
 4,
 4,
 5,
 5,
 4,
 4,
 5,
 4,
 4,
 5,
 5,
 3,
 4,
 3,
 5,
 4,
 4,
 4,
 5,
 4,
 5,
 4,
 5,
 4,
 4,
 4,
 5,
 5,
 5,
 2,
 3,
 3,
 5,
 5,
 4,
 3,
 5,
 4,
 4,
 4,
 2,
 5,
 3,
 3,
 5,
 4,
 4,
 4,
 5,
 5,
 5,
 4,
 4,
 4,
 3,
 3,
 5,
 4,
 4,
 4,
 4,
 5,
 2,
 5,
 4,
 3,
 4,
 4,
 5,
 4,
 5,
 4,
 4,
 4,
 4,
 3,
 4,
 5,
 5,
 4,
 5,
 4,
 5,
 3,
 5,
 3,
 5,
 4,
 5,
 5,
 5,
 2,
 4,
 2,
 3,
 5,
 3,
 4,
 3,
 4,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 4,
 5,
 5,
 4,
 5,
 5,
 5,
 4,
 5,
 3,
 4,
 4,
 4,
 5,
 4,
 5,
 4,
 3,
 5,
 4,
 3,
 5,
 5,
 5,
 4,
 5,
 4,
 4,
 5,
 3,
 5,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 3,
 4,
 3,
 3,
 4,
 5,
 5,
 5,
 4,
 3,
 5,
 4,
 5,
 4,
 4,
 3,
 4,
 3,
 4,
 4,
 5,
 5,
 4,
 5,
 4,
 5,
 5,
 4,
 3,
 5,
 5,
 5,
 5,
 5,
 4,
 3,
 3,
 5,
 3,
 4,
 5,
 5,
 5,
 4,
 4,
 3,
 4,
 5,
 4,
 3,
 5,
 3,
 4,
 3,
 4,
 4,
 5,
 4,
 3,
 5,
 5,
 4,
 3,
 5,
 3,
 5,
 5,
 3,
 3,
 5,
 5,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 4,
 4,
 5,
 5,
 5,
 3,
 5,
 4,
 4,
 5,
 5,
 5,
 3,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 4,
 5,
 5,
 3,
 4,
 5,
 4,
 5,
 3,
 5,
 5,
 4,
 4,
 4,
 4,
 5,
 4,
 4,
 4,
 3,
 4,
 2,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 4,
 5,
 4,
 2,
 3,
 5,
 4,
 5,
 4,
 5,
 5,
 3,
 4,
 4,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 4,
 4,
 3,
 5,
 4,
 5,
 3,
 3,
 4,
 5,
 4,
 4,
 4,
 4,
 2,
 4,
 5,
 5,
 4,
 5,
 4,
 5,
 5,
 5,
 4,
 4,
 5,
 4,
 5,
 2,
 4,
 5,
 3,
 3,
 2,
 4,
 4,
 3,
 3,
 5,
 4,
 3,
 4,
 3,
 5,
 5,
 4,
 3,
 4,
 3,
 5,
 5,
 5,
 4,
 4,
 4,
 5,
 3,
 4,
 4,
 2,
 4,
 4,
 3,
 4,
 4,
 4,
 5,
 5,
 5,
 3,
 5,
 4,
 2,
 5,
 5,
 3,
 5,
 5,
 3,
 5,
 3,
 4,
 5,
 4,
 4,
 4,
 5,
 3,
 1,
 4,
 5,
 5,
 4,
 5,
 4,
 5,
 5,
 5,
 4,
 5,
 4,
 3,
 5,
 4,
 4,
 1,
 5,
 4,
 5,
 4,
 3,
 4,
 3,
 5,
 4,
 5,
 3,
 5,
 3,
 5,
 5,
 4,
 5,
 4,
 5,
 4,
 5,
 3,
 2,
 4,
 5,
 4,
 4,
 4,
 4,
 5,
 4,
 4,
 5,
 5,
 2,
 4,
 2,
 5,
 4,
 3,
 4,
 4,
 4,
 4,
 5,
 5,
 4,
 4,
 4,
 5,
 4,
 4,
 3,
 3,
 5,
 4,
 5,
 5,
 4,
 5,
 4,
 4,
 3,
 4,
 5,
 3,
 5,
 3,
 4,
 3,
 5,
 5,
 4,
 4,
 4,
 3,
 5,
 4,
 4,
 5,
 3,
 5,
 5,
 4,
 5,
 4,
 3,
 5,
 4,
 5,
 4,
 4,
 5,
 4,
 5,
 4,
 5,
 5,
 5,
 4,
 5,
 5,
 4,
 3,
 5,
 5,
 3,
 4,
 3,
 2,
 5,
 5,
 5,
 3,
 4,
 5,
 3,
 4,
 2,
 5,
 5,
 3,
 2,
 5,
 4,
 4,
 4,
 3,
 4,
 5,
 5,
 4,
 2,
 5,
 3,
 3,
 3,
 3,
 5,
 4,
 4,
 5,
 5,
 3,
 4,
 5,
 5,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 5,
 5,
 3,
 4,
 4,
 3,
 3,
 3,
 4,
 3,
 5,
 5,
 5,
 3,
 4,
 3,
 4,
 5,
 4,
 4,
 5,
 5,
 4,
 5,
 4,
 4,
 4,
 3,
 5,
 3,
 5,
 4,
 3,
 5,
 3,
 5,
 5,
 4,
 5,
 4,
 5,
 4,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 5,
 4,
 5,
 4,
 3,
 5,
 5,
 3,
 4,
 5,
 4,
 4,
 4,
 3,
 4,
 5,
 5,
 4,
 5,
 5,
 4,
 4,
 4,
 3,
 4,
 4,
 1,
 5,
 5,
 4,
 5,
 5,
 5,
 4,
 5,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 4,
 5,
 5,
 4,
 5,
 4,
 3,
 5,
 4,
 5,
 3,
 5,
 3,
 5,
 4,
 3,
 4,
 3,
 5,
 3,
 3,
 4,
 4,
 5,
 3,
 4,
 3,
 5,
 4,
 5,
 5,
 5,
 5,
 5,
 4,
 3,
 5,
 5,
 4,
 3,
 3,
 3,
 5,
 4,
 4,
 5,
 5,
 4,
 3,
 2,
 3,
 3,
 4,
 4,
 5,
 2,
 5,
 5,
 4,
 2,
 4,
 5,
 4,
 3,
 4,
 4,
 5,
 2,
 4,
 5,
 3,
 4,
 4,
 4,
 3,
 4,
 4,
 4,
 4,
 5,
 5,
 3,
 4,
 4,
 4,
 3,
 4,
 4,
 5,
 5,
 4,
 3,
 4,
 5,
 4,
 4,
 5,
 4,
 3,
 5,
 3,
 4,
 4,
 4,
 5,
 4,
 3,
 5,
 4,
 3,
 4,
 3,
 4,
 5,
 3,
 3,
 5,
 4,
 3,
 3,
 4,
 4,
 5,
 5,
 5,
 5,
 1,
 4,
 4,
 4,
 3,
 4,
 5,
 3,
 4,
 4,
 4,
 4,
 5,
 4,
 4,
 5,
 5,
 3,
 4,
 5,
 4,
 4,
 3,
 5,
 3,
 5,
 5,
 4,
 5,
 4,
 5,
 5,
 5,
 4,
 5,
 5,
 4,
 4,
 5,
 5,
 5,
 5,
 4,
 4,
 2,
 5,
 4,
 4,
 4,
 5,
 5,
 5,
 4,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 1,
 4,
 5,
 4,
 4,
 5,
 5,
 5,
 4,
 4,
 4,
 5,
 4,
 4,
 4,
 4,
 3,
 5,
 5,
 3,
 3,
 5,
 2,
 3,
 5,
 4,
 3,
 5,
 3,
 2,
 5,
 5,
 4,
 4,
 4,
 5,
 4,
 5,
 4,
 5,
 5,
 3,
 4,
 5,
 4,
 4,
 4,
 5,
 5,
 2,
 3,
 5,
 4,
 3,
 5,
 4,
 4,
 3,
 5,
 4,
 4,
 5,
 3,
 4,
 5,
 3,
 4,
 4,
 5,
 5,
 5,
 4,
 4,
 4,
 5,
 3,
 5,
 4,
 5,
 5,
 3,
 4,
 4,
 5,
 4,
 4,
 5,
 5,
 4,
 5,
 4,
 5,
 5,
 3,
 4,
 ...]

In [27]:
len(Master_Data[Master_Data["Title"].str.contains("Toy Story")]["Rating"].tolist())

3662

In [30]:
Master_Data[Master_Data["Title"].str.contains("Toy Story")][:20]

,UserID,Gender,Age,Occupation,Zip-code,MovieID,Rating,Timestamp,Title,Genres
41626,1,F,1,10,48067,1,5,978824268,Toy Story (1995),Animation|Children's|Comedy
41627,6,F,50,9,55117,1,4,978237008,Toy Story (1995),Animation|Children's|Comedy
41628,8,M,25,12,11413,1,4,978233496,Toy Story (1995),Animation|Children's|Comedy
41629,9,M,25,17,61614,1,5,978225952,Toy Story (1995),Animation|Children's|Comedy
41630,10,F,35,1,95370,1,5,978226474,Toy Story (1995),Animation|Children's|Comedy
41631,18,F,18,3,95825,1,4,978154768,Toy Story (1995),Animation|Children's|Comedy
41632,19,M,1,10,48073,1,5,978555994,Toy Story (1995),Animation|Children's|Comedy
41633,21,M,18,16,99353,1,3,978139347,Toy Story (1995),Animation|Children's|Comedy
41634,23,M,35,0,90049,1,4,978463614,Toy Story (1995),Animation|Children's|Comedy
41635,26,M,25,7,23112,1,3,978130703,Toy Story (1995),Animation|Children's|Comedy
41636,28,F,25,1,14607,1,3,978985309,Toy Story (1995),Animation|Children's|Comedy
41637,34,F,18,0,02135,1,5,978102970,Toy Story (1995),Animation|Children's|Comedy
41638,36,M,25,3,94123,1,5,978061285,Toy Story (1995),Animation|Children's|Comedy
41639,38,F,18,4,02215,1,5,978046225,Toy Story (1995),Animation|Children's|Comedy
41640,44,M,45,17,98052,1,5,978019369,Toy Story (1995),Animation|Children's|Comedy
41641,45,F,45,16,94110,1,4,977990044,Toy Story (1995),Animation|Children's|Comedy
41642,48,M,25,4,92107,1,4,977975909,Toy Story (1995),Animation|Children's|Comedy
41643,49,M,18,12,77084,1,5,977972501,Toy Story (1995),Animation|Children's|Comedy
41644,51,F,1,10,10562,1,5,977947828,Toy Story (1995),Animation|Children's|Comedy
41645,56,M,35,20,60440,1,5,977938855,Toy Story (1995),Animation|Children's|Comedy

In [31]:
Master_Data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000209 entries, 0 to 1000208
Data columns (total 10 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   UserID      1000209 non-null  int64
 1   Gender      1000209 non-null  object
 2   Age         1000209 non-null  int64
 3   Occupation  1000209 non-null  int64
 4   Zip-code    1000209 non-null  object
 5   MovieID     1000209 non-null  int64
 6   Rating      1000209 non-null  int64
 7   Timestamp   1000209 non-null  int64
 8   Title       1000209 non-null  object
 9   Genres      1000209 non-null  object
dtypes: int64(6), object(4)
memory usage: 83.9+ MB

In [33]:
Master_Data["Movie"] = Master_Data['Title'].str.split('(', 1).str[0].str.strip()

In [34]:
Master_Data["Movie"].unique().tolist()

["One Flew Over the Cuckoo's Nest",
 'James and the Giant Peach',
 'My Fair Lady',
 'Erin Brockovich',
 "Bug's Life, A",
 'Princess Bride, The',
 'Ben-Hur',
 'Christmas Story, A',
 'Snow White and the Seven Dwarfs',
 'Wizard of Oz, The',
 'Beauty and the Beast',
 'Gigi',
 'Miracle on 34th Street',
 "Ferris Bueller's Day Off",
 'Sound of Music, The',
 'Airplane!',
 'Tarzan',
 'Bambi',
 'Awakenings',
 'Big',
 'Pleasantville',
 'Wallace & Gromit: The Best of Aardman Animation',
 'Back to the Future',
 "Schindler's List",
 'Meet Joe Black',
 'Pocahontas',
 'E.T. the Extra-Terrestrial',
 'Titanic',
 'Ponette',
 'Close Shave, A',
 'Antz',
 'Girl, Interrupted',
 'Hercules',
 'Aladdin',
 'Mulan',
 'Hunchback of Notre Dame, The',
 'Last Days of Disco, The',
 'Cinderella',
 'Sixth Sense, The',
 'Apollo 13',
 'Toy Story',
 'Rain Man',
 'Driving Miss Daisy',
 'Run Lola Run',
 'Star Wars: Episode IV - A New Hope',
 'Mary Poppins',
 'Dumbo',
 'To Kill a Mockingbird',
 'Saving Private Ryan',
 'Secret Garden, The',
 'Toy Story 2',
 'Fargo',
 'Dead Poets Society',
 'Shine',
 'Verdict, The',
 'Shall We Dance?',
 'Courage Under Fire',
 'Untouchables, The',
 'Mission: Impossible',
 'Few Good Men, A',
 'Star Wars: Episode I - The Phantom Menace',
 'Rebel Without a Cause',
 'Total Recall',
 'Hustler, The',
 'Star Wars: Episode VI - Return of the Jedi',
 'U.S. Marshalls',
 'Jackal, The',
 'GoodFellas',
 'Gladiator',
 'Double Jeopardy',
 'Yojimbo',
 'Ran',
 'Cliffhanger',
 'Snake Eyes',
 'Backdraft',
 'Fisher King, The',
 'Mister Roberts',
 'Day the Earth Stood Still, The',
 'Hunt for Red October, The',
 'Outbreak',
 'Simon Birch',
 'Stand and Deliver',
 "Breakfast at Tiffany's",
 'Maverick',
 'Stand by Me',
 'Green Mile, The',
 'Lost World: Jurassic Park, The',
 'Gandhi',
 'Strictly Ballroom',
 'League of Their Own, A',
 'Patriot Games',
 'Bodyguard, The',
 'Braveheart',
 'Ronin',
 'Payback',
 'Spanish Prisoner, The',
 'Close Encounters of the Third Kind',
 'Terminator 2: Judgment Day',
 'Alien: Resurrection',
 'Guns of Navarone, The',
 "Soldier's Story, A",
 'On the Waterfront',
 'Picnic',
 'Misérables, Les',
 'American Beauty',
 'Amadeus',
 'Remains of the Day, The',
 'Demolition Man',
 'Children of a Lesser God',
 'Like Water for Chocolate',
 'Last of the Mohicans, The',
 'Bonnie and Clyde',
 'Starman',
 'Jurassic Park',
 'Prefontaine',
 'Doctor Zhivago',
 'Groundhog Day',
 'Die Hard 2',
 'Man in the Iron Mask, The',
 'Star Trek VI: The Undiscovered Country',
 'Enemy of the State',
 'Key Largo',
 'Thin Red Line, The',
 'Dances with Wolves',
 'Star Wars: Episode V - The Empire Strikes Back',
 'Con Air',
 'Twister',
 'Raiders of the Lost Ark',
 'Silence of the Lambs, The',
 'Waking Ned Devine',
 'Broken Arrow',
 'Ghostbusters II',
 'Matrix, The',
 'Armageddon',
 'Shakespeare in Love',
 'Serpico',
 'French Connection, The',
 'Conspiracy Theory',
 'What About Bob?',
 'Rocky',
 'Kramer Vs. Kramer',
 'Ed Wood',
 'On Golden Pond',
 'Chariots of Fire',
 'Desperado',
 'Get Shorty',
 'Die Hard: With a Vengeance',
 'Platoon',
 'True Lies',
 'October Sky',
 'Clear and Present Danger',
 'Fugitive, The',
 "Sophie's Choice",
 'Gone with the Wind',
 'Getaway, The',
 'Fifth Element, The',
 'Thelma & Louise',
 'Under Siege',
 "Guess Who's Coming to Dinner",
 'Grapes of Wrath, The',
 'Independence Day',
 'Mr. Jones',
 'Spartacus',
 'Lethal Weapon 3',
 'As Good As It Gets',
 'Indochine',
 'Mask of Zorro, The',
 'Shawshank Redemption, The',
 'Breakfast Club, The',
 'Man with the Golden Arm, The',
 'Manhattan',
 'Forrest Gump',
 "Miller's Crossing",
 'Nurse Betty',
 'Graduate, The',
 'Animal House',
 'Full Monty, The',
 'Raising Arizona',
 '28 Days',
 'Happy Gilmore',
 'Golden Child, The',
 'Beverly Hills Ninja',
 'Naked Gun: From the Files of Police Squad!, The',
 'Fish Called Wanda, A',
 'Being John Malkovich',
 'Edge, The',
 'Indiana Jones and the Last Crusade',
 'Dragonheart',
 'Blade',
 'Men in Black',
 'Hollywood Knights, The',
 'Ghost and the Darkness, The',
 'Evil Dead II',
 'Three Musketeers, The',
 'Unforgiven',
 'Rock, The',
 'Young Guns',
 'Young Guns II',
 'Caddyshack',
 'Butch Cassidy and the Sundance Kid',
 'Crocodile Dundee',
 'Easy Rider',
 'Mummy, The',
 'Blazing Saddles',
 'Deliverance',
 'Indiana Jones and the Temple of Doom',
 'Monty Python and the Holy Grail',
 'Little Mermaid, The',
 'Fistful of Dollars, A',
 'Alien',
 'Die Hard',
 'Mad Max',
 'King Kong',
 'Jaws',
 'Predator',
 'Good, The Bad and The Ugly, The',
 'Goldfinger',
 'Terminator, The',
 'Who Framed Roger Rabbit?',
 'Gods and Monsters',
 'Delicatessen',
 'Clueless',
 'Natural Born Killers',
 'Velvet Goldmine',
 'Love! Valour! Compassion!',
 'Citizen Ruth',
 'Donnie Brasco',
 'Maybe, Maybe Not',
 'Wings of the Dove, The',
 'Bound',
 'Mrs. Dalloway',
 'Bowfinger',
 'Before Sunrise',
 'Four Days in September',
 'Naked',
 'Orlando',
 'Bridge on the River Kwai, The',
 'X-Men',
 'Piano, The',
 'Richard III',
 'Negotiator, The',
 'Pokémon the Movie 2000',
 'Seven',
 'South Park: Bigger, Longer and Uncut',
 'Pulp Fiction',
 'Celluloid Closet, The',
 'L.A. Confidential',
 'Cold Comfort Farm',
 'Priest',
 'Mansfield Park',
 'Ravenous',
 'X-Files: Fight the Future, The',
 'Don Juan DeMarco',
 'One False Move',
 'Death and the Maiden',
 'Heat',
 'Insider, The',
 'Beautiful Thing',
 'Lone Star',
 'Usual Suspects, The',
 'Mighty Aphrodite',
 'Madonna: Truth or Dare',
 'Paris Is Burning',
 'Sleepy Hollow',
 'Speed',
 'Pump Up the Volume',
 'All About My Mother',
 'Rules of Engagement',
 'Faculty, The',
 'Pecker',
 "Joe Gould's Secret",
 'Pillow Book, The',
 'Out of Sight',
 'Ghostbusters',
 'Liar Liar',
 'Player, The',
 'Crumb',
 'Abyss, The',
 'Creepshow',
 'Tender Mercies',
 'Good Will Hunting',
 'Topsy-Turvy',
 'Wilde',
 'Edward Scissorhands',
 'Ice Storm, The',
 'Night on Earth',
 'Trick',
 'Mystery Men',
 'Pi',
 'Twin Falls Idaho',
 "There's Something About Mary",
 'Go',
 'JFK',
 'Shaft',
 'Night of the Living Dead',
 'Wild Reeds',
 'Falling Down',
 'Men With Guns',
 'Living in Oblivion',
 'Go Fish',
 "Jackie Chan's First Strike",
 'Henry: Portrait of a Serial Killer',
 'Office Killer',
 'Mrs. Brown',
 'Hand That Rocks the Cradle, The',
 'Talented Mr. Ripley, The',
 'Sweet Hereafter, The',
 'Teaching Mrs. Tingle',
 'Mosquito Coast, The',
 'Fast, Cheap & Out of Control',
 'Strawberry and Chocolate',
 'Poseidon Adventure, The',
 'River Runs Through It, A',
 'Hard 8',
 'Love and Death on Long Island',
 'Election',
 'Grosse Pointe Blank',
 'Fight Club',
 'All Over Me',
 'Tomorrow Never Dies',
 'Washington Square',
 'North by Northwest',
 'Gattaca',
 'Babe: Pig in the City',
 'Jackie Brown',
 "Jacob's Ladder",
 'Three Kings',
 'End of Days',
 'Casino',
 "Billy's Hollywood Screen Kiss",
 'Smoke',
 'Nightmare Before Christmas, The',
 "Romy and Michele's High School Reunion",
 'Incredibly True Adventure of Two Girls in Love, The',
 'Happiness',
 'Austin Powers: International Man of Mystery',
 'Reservoir Dogs',
 'Howards End',
 'Maltese Falcon, The',
 'Kundun',
 'Final Destination',
 'Get Real',
 'Waiting for Guffman',
 'Big Lebowski, The',
 'Afterglow',
 'Little Voice',
 'My Life in Pink',
 'Man Bites Dog',
 'Mariachi, El',
 'Shanghai Noon',
 'Rushmore',
 'In the Company of Men',
 'Austin Powers: The Spy Who Shagged Me',
 'Age of Innocence, The',
 'Dick',
 'Big Night',
 'Fear and Loathing in Las Vegas',
 'Opposite of Sex, The',
 'Madness of King George, The',
 'Powder',
 'Anywhere But Here',
 'Bullets Over Broadway',
 'Cruise, The',
 'Doors, The',
 'City of Lost Children, The',
 'Welcome to the Dollhouse',
 'Glengarry Glen Ross',
 'Nowhere',
 '54',
 'Much Ado About Nothing',
 'Total Eclipse',
 'Wag the Dog',
 "Boys Don't Cry",
 'Metropolitan',
 'Misery',
 'Crow, The',
 'Twelve Monkeys',
 'Rosencrantz and Guildenstern Are Dead',
 'High Art',
 'Bob Roberts',
 "But I'm a Cheerleader",
 'Babe',
 'Four Weddings and a Funeral',
 'Dead Man Walking',
 'Dead Man',
 'Romancing the Stone',
 'Top Gun',
 'Gone in 60 Seconds',
 "Pete's Dragon",
 'Anastasia',
 'Lion King, The',
 "Murphy's Romance",
 'Moonstruck',
 'Jeremiah Johnson',
 'Outlaw Josey Wales, The',
 'To Gillian on Her 37th Birthday',
 'Pretty Woman',
 'Wyatt Earp',
 'Other Sister, The',
 'Arthur',
 "My Best Friend's Wedding",
 'Mighty Ducks, The',
 'Blue Hawaii',
 'Gypsy',
 'Tequila Sunrise',
 'Keeping the Faith',
 'Patriot, The',
 'Magnum Force',
 'Babes in Toyland',
 "Prizzi's Honor",
 'Roustabout',
 'Room with a View, A',
 'Emma',
 'Apple Dumpling Gang, The',
 'West Side Story',
 'Straight Story, The',
 'Legends of the Fall',
 'Sense and Sensibility',
 'Benny & Joon',
 'Dirty Dancing',
 'Casablanca',
 'Umbrellas of Cherbourg, The',
 'Paulie',
 'Peggy Sue Got Married',
 'Splash',
 'Out of Africa',
 'Grease',
 'Little Big League',
 'Witness',
 'Where the Heart Is',
 'Supercop',
 'Exorcist, The',
 'Face/Off',
 'In the Line of Fire',
 'Godfather: Part II, The',
 'Elizabeth',
 "Mo' Better Blues",
 'Jerry Maguire',
 'Truman Show, The',
 'Philadelphia',
 'Batman: Mask of the Phantasm',
 'Dead Presidents',
 'Moll Flanders',
 'Mr. Saturday Night',
 'Cider House Rules, The',
 'Summer of Sam',
 'Private Parts',
 'Amistad',
 'Rob Roy',
 'Poetic Justice',
 'Waiting to Exhale',
 'Soul Food',
 'Anna and the King',
 'Postino, Il',
 'Eyes Wide Shut',
 'Mighty Joe Young',
 'He Got Game',
 'Buffalo 66',
 "Devil's Own, The",
 'Dolores Claiborne',
 'People vs. Larry Flynt, The',
 'Crimson Tide',
 'Hamlet',
 'Rudy',
 "William Shakespeare's Romeo and Juliet",
 'Firm, The',
 'Deconstructing Harry',
 'Akira',
 'Ghost in the Shell',
 'Cyrano de Bergerac',
 'Chasing Amy',
 'Prince of Tides, The',
 'What Dreams May Come',
 'Heaven & Earth',
 'Midnight in the Garden of Good and Evil',
 'Six Degrees of Separation',
 'Street Fighter',
 'Hilary and Jackie',
 'Malcolm X',
 'Any Given Sunday',
 'Bridges of Madison County, The',
 'Interview with the Vampire',
 'Alive',
 'Scent of a Woman',
 'Inkwell, The',
 'Taxi Driver',
 'Far and Away',
 'Cop Land',
 'Godfather: Part III, The',
 'Nixon',
 "What's Eating Gilbert Grape",
 'Beloved',
 'eXistenZ',
 'My Crazy Life',
 'True Romance',
 "Eve's Bayou",
 'Hard-Boiled',
 'Great Expectations',
 'High Fidelity',
 'Red Violin, The',
 "General's Daughter, The",
 'Adventures of Priscilla, Queen of the Desert, The',
 'Apt Pupil',
 'Leaving Las Vegas',
 'Life Is Beautiful',
 'American History X',
 'Primary Colors',
 'Cruel Intentions',
 'Boogie Nights',
 'Joy Luck Club, The',
 'Robin Hood: Prince of Thieves',
 'Arachnophobia',
 'Nell',
 'Mask, The',
 'Clerks',
 'Boiler Room',
 'Meet the Parents',
 'Time to Kill, A',
 'Frequency',
 'Quiz Show',
 'Wedding Singer, The',
 'Whole Nine Yards, The',
 'Cape Fear',
 'Magnolia',
 'Searching for Bobby Fischer',
 'Romeo Must Die',
 'Swingers',
 'Star Trek: First Contact',
 'Sling Blade',
 'Hurricane, The',
 'Chicken Run',
 'Hollow Man',
 'Perfect Storm, The',
 'My Cousin Vinny',
 'Wrong Trousers, The',
 'Return to Paradise',
 "Wayne's World",
 'Contact',
 'Grand Day Out, A',
 'Kolya',
 'Mission: Impossible 2',
 'Trainspotting',
 'Tango Lesson, The',
 'Skulls, The',
 'Remember the Titans',
 'Boat, The',
 'When Harry Met Sally...',
 'Cutting Edge, The',
 'Hype!',
 'Bronx Tale, A',
 "Midsummer Night's Dream, A",
 'Defending Your Life',
 'Breaking Away',
 'Prophecy II, The',
 'Alien³',
 'Addams Family, The',
 'Ever After: A Cinderella Story',
 'Honey, I Shrunk the Kids',
 'Chinatown',
 'Treasure of the Sierra Madre, The',
 'Naked Gun 2 1/2: The Smell of Fear, The',
 'Duck Soup',
 'Better Off Dead...',
 'Lost in Space',
 'American Graffiti',
 'Home Alone',
 'Ghost',
 'Teenage Mutant Ninja Turtles',
 'Teenage Mutant Ninja Turtles II: The Secret of the Ooze',
 'To Sir with Love',
 'Blast from the Past',
 'Message in a Bottle',
 'Jumanji',
 'My Favorite Martian',
 'Batman Forever',
 'Sabrina',
 'Adventures in Babysitting',
 'Doctor Dolittle',
 'Nutty Professor, The',
 "Charlotte's Web",
 'Phenomenon',
 'Watership Down',
 'Michael',
 "Bram Stoker's Dracula",
 'Arsenic and Old Lace',
 'Superman',
 'Batman',
 'Pinocchio',
 'Good Earth, The',
 'Lethal Weapon 4',
 'Dark Crystal, The',
 "'burbs, The",
 'Fried Green Tomatoes',
 'Carrie',
 'Journey of Natty Gann, The',
 'Jungle Book, The',
 'Cool Hand Luke',
 'Spy Hard',
 'Mystery Science Theater 3000: The Movie',
 'Young Frankenstein',
 'Bachelor Party',
 'All Quiet on the Western Front',
 'Rocky Horror Picture Show, The',
 'Harry and the Hendersons',
 'Stargate',
 'Santa Clause, The',
 'Houseguest',
 'Lady and the Tramp',
 'Fantasia',
 'High Noon',
 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
 'Peter Pan',
 'Somewhere in Time',
 "Pee-wee's Big Adventure",
 'War of the Worlds, The',
 'Heart and Souls',
 'Producers, The',
 'Mallrats',
 'Star Trek: Generations',
 'Robin Hood',
 'Nine Months',
 'NeverEnding Story, The',
 'Little Big Man',
 'Rescuers, The',
 'Trading Places',
 'Return from Witch Mountain',
 'First Wives Club, The',
 'Return to Oz',
 'Rear Window',
 'Rocketeer, The',
 'Being There',
 'Sleeping Beauty',
 'M*A*S*H',
 'Jack',
 'Little Shop of Horrors',
 'Escape to Witch Mountain',
 'Tom Jones',
 'Tommy Boy',
 'While You Were Sleeping',
 'Practical Magic',
 'Star Trek: The Motion Picture',
 'Beetlejuice',
 'Star Trek: The Wrath of Khan',
 'Star Trek III: The Search for Spock',
 'Star Trek IV: The Voyage Home',
 'Batman Returns',
 'Roman Holiday',
 'Meet Me in St. Louis',
 'Old Yeller',
 '13th Warrior, The',
 'Gold Rush, The',
 'Homeward Bound: The Incredible Journey',
 'Shaggy Dog, The',
 '20,000 Leagues Under the Sea',
 'Hook',
 'Ace Ventura: Pet Detective',
 'Mixed Nuts',
 'Hero',
 'Citizen Kane',
 '2001: A Space Odyssey',
 'Alien Nation',
 'Mad Max 2',
 'All About Eve',
 'Mad Max Beyond Thunderdome',
 'Cool Runnings',
 'Cable Guy, The',
 'Godfather, The',
 'Winnie the Pooh and the Blustery Day',
 'Sword in the Stone, The',
 'Trekkies',
 'Labyrinth',
 'Corrina, Corrina',
 'Jewel of the Nile, The',
 'Cocoon',
 'Tora! Tora! Tora!',
 'Willow',
 'Affair to Remember, An',
 'Bedknobs and Broomsticks',
 'Streetcar Named Desire, A',
 'Alice in Wonderland',
 'Coneheads',
 'Ghost and Mrs. Muir, The',
 'That Thing You Do!',
 'Naked Gun 33 1/3: The Final Insult',
 'Christmas Vacation',
 '7th Voyage of Sinbad, The',
 "You've Got Mail",
 'March of the Wooden Soldiers',
 'Scrooged',
 "It's a Wonderful Life",
 'Mr. Smith Goes to Washington',
 'Mr. Mom',
 "Hard Day's Night, A",
 'Battlefield Earth',
 'Return of the Pink Panther, The',
 'Robin Hood: Men in Tights',
 'Romeo and Juliet',
 'Vacation',
 'Escape from New York',
 'Patch Adams',
 "Mr. Holland's Opus",
 "Dog's Life, A",
 "Ulee's Gold",
 'Tea with Mussolini',
 'Shop Around the Corner, The',
 'Shampoo',
 'Everything You Always Wanted to Know About Sex',
 'Lethal Weapon',
 'Inspector General, The',
 'Lethal Weapon 2',
 'Aliens',
 'Gremlins',
 '12 Angry Men',
 'Goonies, The',
 'Lawrence of Arabia',
 'African Queen, The',
 'Excalibur',
 'White Christmas',
 'Help!',
 'Philadelphia Story, The',
 'Soylent Green',
 'Pajama Game, The',
 "Singin' in the Rain",
 'Private Benjamin',
 'From Russia with Love',
 'Sleepless in Seattle',
 'Fletch',
 'Sister Act',
 'Man on the Moon',
 'Galaxy Quest',
 'Money Pit, The',
 'Police Academy',
 'Cat on a Hot Tin Roof',
 'Back to the Future Part II',
 'Back to the Future Part III',
 'Absent Minded Professor, The',
 'Army of Darkness',
 'Willy Wonka and the Chocolate Factory',
 "Porky's",
 'Blade Runner',
 'Son in Law',
 'So I Married an Axe Murderer',
 "Wayne's World 2",
 'Boy Who Could Fly, The',
 'Planet of the Apes',
 'FairyTale: A True Story',
 'Simple Wish, A',
 'My Dog Skip',
 'Anne Frank Remembered',
 'G.I. Jane',
 'Dune',
 'Blues Brothers, The',
 "Monty Python's Life of Brian",
 'Bad Seed, The',
 'Time Bandits',
 'Beneath the Planet of the Apes',
 'Buffy the Vampire Slayer',
 'Way We Were, The',
 'Star Trek: Insurrection',
 'Papillon',
 'Santa Claus: The Movie',
 'Field of Dreams',
 'Annie Hall',
 'Tron',
 'Black Cauldron, The',
 'L.A. Story',
 'Sting, The',
 'Jerk, The',
 "Weekend at Bernie's",
 'Never Cry Wolf',
 'To Wong Foo, Thanks for Everything! Julie Newmar',
 'Starship Troopers',
 'Waterworld',
 'Man with Two Brains, The',
 'Computer Wore Tennis Shoes, The',
 'Condorman',
 'Abbott and Costello Meet Frankenstein',
 "Darby O'Gill and the Little People",
 'Far Off Place, A',
 'Flight of the Navigator',
 'Gnome-Mobile, The',
 'Happiest Millionaire, The',
 'Half Baked',
 'Billy Madison',
 'American Pie',
 'Mommie Dearest',
 'Blair Witch Project, The',
 'Kids in the Hall: Brain Candy',
 'Good Morning, Vietnam',
 'Dumb & Dumber',
 'Blue Velvet',
 'Hoop Dreams',
 'Immortal Beloved',
 'This Is Spinal Tap',
 'Muppet Movie, The',
 'Fatal Attraction',
 'Pushing Tin',
 'Holy Man',
 'Heavy',
 "Muriel's Wedding",
 'Almost Heroes',
 'Orgazmo',
 'Sweet and Lowdown',
 'Superstar',
 'Adventures of Sebastian Cole, The',
 'Waterboy, The',
 'Vegas Vacation',
 'Deuce Bigalow: Male Gigolo',
 'Schizopolis',
 'Dave',
 'Dazed and Confused',
 'Breakfast of Champions',
 'Dream With the Fishes',
 'Inventing the Abbotts',
 'Mumford',
 'Mr. Death: The Rise and Fall of Fred A. Leuchter Jr.',
 'Angels and Insects',
 'Black Sheep',
 'Fly Away Home',
 'Kalifornia',
 'Analyze This',
 'Bean',
 'Swing Kids',
 'Truth About Cats & Dogs, The',
 'Dog Day Afternoon',
 'Larger Than Life',
 'Almost Famous',
 'Father of the Bride',
 'Quatermass and the Pit',
 'Man Who Would Be King, The',
 '2 Days in the Valley',
 'Dick Tracy',
 'Scary Movie',
 'Audrey Rose',
 'Great Escape, The',
 'Superman II',
 'Quest for Fire',
 'Ladyhawke',
 'GoldenEye',
 'Medicine Man',
 'True Grit',
 'Black Beauty',
 'Adventures of Buckaroo Bonzai Across the 8th Dimension, The',
 'Young Sherlock Holmes',
 'Saint, The',
 'Rising Sun',
 'Around the World in 80 Days',
 'Indian in the Cupboard, The',
 'Titan A.E.',
 'Emerald Forest, The',
 'Big Blue, The',
 "Logan's Run",
 'Conan the Barbarian',
 'Forever Young',
 'Crimson Pirate, The',
 'Mission to Mars',
 'Deer Hunter, The',
 '10 Things I Hate About You',
 '400 Blows, The',
 'Spaceballs',
 'Broadcast News',
 'Big Daddy',
 'Children of Paradise',
 'Halloween',
 'Bringing Out the Dead',
 "She's All That",
 'Birdcage, The',
 'What Lies Beneath',
 'Arlington Road',
 'EDtv',
 'Bachelor, The',
 'Bone Collector, The',
 'Haunting, The',
 'Congo',
 'Arrival, The',
 'Runaway Bride',
 'Never Been Kissed',
 'Palmetto',
 'Murder at 1600',
 'Lord of the Flies',
 'American Psycho',
 'Just Cause',
 'Ransom',
 'Striptease',
 'Instinct',
 'Bulworth',
 'Thomas Crown Affair, The',
 'Big Kahuna, The',
 'Perfect Murder, A',
 'Air Force One',
 'Sneakers',
 'Stigmata',
 'Stir of Echoes',
 "Big Momma's House",
 'Mrs. Doubtfire',
 'Cradle Will Rock, The',
 'One True Thing',
 'Rush Hour',
 'Seven Years in Tibet',
 'Game, The',
 'Selena',
 'Flubber',
 'Civil Action, A',
 'From Dusk Till Dawn',
 'I Know What You Did Last Summer',
 "Devil's Advocate, The",
 'Jakob the Liar',
 'Very Bad Things',
 'Psycho',
 'Story of Us, The',
 'Tombstone',
 'Primal Fear',
 'Singles',
 'Entrapment',
 'Newton Boys, The',
 'Wild Things',
 'Simple Plan, A',
 'Prince of Egypt, The',
 'House Party',
 'Basic Instinct',
 'Rainmaker, The',
 'Baby Geniuses',
 'Love Letter, The',
 'Wild Wild West',
 'Mod Squad, The',
 'Lake Placid',
 'Bell, Book and Candle',
 'Superman IV: The Quest for Peace',
 'Inspector Gadget',
 'Deep Blue Sea',
 'Mickey Blue Eyes',
 'Dudley Do-Right',
 'Iron Giant, The',
 'I Saw What You Did',
 'Desperately Seeking Susan',
 'Drive Me Crazy',
 'Jack Frost',
 'Best Man, The',
 'Grifters, The',
 'Village of the Damned',
 'Children of the Damned',
 'Invisible Man, The',
 'Cell, The',
 'My Left Foot',
 'Solaris',
 'Art of War, The',
 'Destination Moon',
 'Sphere',
 'Devil in a Blue Dress',
 'Waking the Dead',
 'Shallow Grave',
 'Heavenly Creatures',
 'Angel Baby',
 'Big Sleep, The',
 'Thing From Another World, The',
 'It Came from Outer Space',
 'It Came from Beneath the Sea',

In [35]:
best_rating = Master_Data[Master_Data["Rating"]==Master_Data["Rating"].max()]

In [36]:
best_rating.groupby(["Movie"]).Rating.max()[:25]

Movie
$1,000,000 Duck                 5
'Night Mother                   5
'Til There Was You              5
'burbs, The                     5
...And Justice for All          5
10 Things I Hate About You      5
101 Dalmatians                  5
12 Angry Men                    5
13th Warrior, The               5
187                             5
2 Days in the Valley            5
20 Dates                        5
20,000 Leagues Under the Sea    5
200 Cigarettes                  5
2001: A Space Odyssey           5
2010                            5
24 7: Twenty Four Seven         5
28 Days                         5
39 Steps, The                   5
400 Blows, The                  5
42 Up                           5
52 Pick-Up                      5
54                              5
7th Voyage of Sinbad, The       5
8 1/2                           5
Name: Rating, dtype: int64

In [37]:
Master_Data[Master_Data["UserID"]==2696]

,UserID,Gender,Age,Occupation,Zip-code,MovieID,Rating,Timestamp,Title,Genres,Movies,Movie
24345,2696,M,25,7,24210,1270,2,973308676,Back to the Future (1985),Comedy|Sci-Fi,Back to the Future,Back to the Future
29848,2696,M,25,7,24210,1097,3,973308690,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi,E.T. the Extra-Terrestrial,E.T. the Extra-Terrestrial
244232,2696,M,25,7,24210,1617,4,973308842,L.A. Confidential (1997),Crime|Film-Noir|Mystery|Thriller,L.A. Confidential,L.A. Confidential
250014,2696,M,25,7,24210,800,5,973308842,Lone Star (1996),Drama|Mystery,Lone Star,Lone Star
273633,2696,M,25,7,24210,3386,1,973308842,JFK (1991),Drama|Mystery,JFK,JFK
277808,2696,M,25,7,24210,3176,4,973308865,"Talented Mr. Ripley, The (1999)",Drama|Mystery|Thriller,"Talented Mr. Ripley, The","Talented Mr. Ripley, The"
371178,2696,M,25,7,24210,1711,4,973308904,Midnight in the Garden of Good and Evil (1997),Comedy|Crime|Drama|Mystery,Midnight in the Garden of Good and Evil,Midnight in the Garden of Good and Evil
377250,2696,M,25,7,24210,1589,3,973308865,Cop Land (1997),Crime|Drama|Mystery,Cop Land,Cop Land
598042,2696,M,25,7,24210,1783,4,973308865,Palmetto (1998),Film-Noir|Mystery|Thriller,Palmetto,Palmetto
603189,2696,M,25,7,24210,1892,4,973308904,"Perfect Murder, A (1998)",Mystery|Thriller,"Perfect Murder, A","Perfect Murder, A"
609204,2696,M,25,7,24210,1625,4,973308842,"Game, The (1997)",Mystery|Thriller,"Game, The","Game, The"
611956,2696,M,25,7,24210,1644,2,973308920,I Know What You Did Last Summer (1997),Horror|Mystery|Thriller,I Know What You Did Last Summer,I Know What You Did Last Summer
612552,2696,M,25,7,24210,1645,4,973308904,"Devil's Advocate, The (1997)",Crime|Horror|Mystery|Thriller,"Devil's Advocate, The","Devil's Advocate, The"
613486,2696,M,25,7,24210,2389,4,973308710,Psycho (1998),Crime|Horror|Thriller,Psycho,Psycho
616546,2696,M,25,7,24210,1805,4,973308886,Wild Things (1998),Crime|Drama|Mystery|Thriller,Wild Things,Wild Things
618708,2696,M,25,7,24210,1092,4,973308886,Basic Instinct (1992),Mystery|Thriller,Basic Instinct,Basic Instinct
621101,2696,M,25,7,24210,2713,1,973308710,Lake Placid (1999),Horror|Thriller,Lake Placid,Lake Placid
689379,2696,M,25,7,24210,1258,4,973308710,"Shining, The (1980)",Horror,"Shining, The","Shining, The"
697451,2696,M,25,7,24210,2338,2,973308920,I Still Know What You Did Last Summer (1998),Horror|Mystery|Thriller,I Still Know What You Did Last Summer,I Still Know What You Did Last Summer
777089,2696,M,25,7,24210,350,3,973308886,"Client, The (1994)",Drama|Mystery|Thriller,"Client, The","Client, The"

In [38]:
genres = pd.DataFrame(Master_Data["Genres"].str.split("|").tolist()).stack()

In [39]:
genres.value_counts()

Comedy         356580
Drama          354529
Action         257457
Thriller       189680
Sci-Fi         157294
Romance        147523
Adventure      133953
Crime           79541
Horror          76386
Children's      72186
War             68527
Animation       43293
Musical         41533
Mystery         40178
Fantasy         36301
Western         20683
Film-Noir       18261
Documentary      7910
dtype: int64

In [40]:
total_genres = genres.unique().tolist()

In [41]:
total_genres

['Drama',
 'Animation',
 "Children's",
 'Musical',
 'Romance',
 'Comedy',
 'Action',
 'Adventure',
 'Fantasy',
 'Sci-Fi',
 'War',
 'Thriller',
 'Crime',
 'Mystery',
 'Western',
 'Horror',
 'Film-Noir',
 'Documentary']

In [42]:
for label in total_genres:
    Master_Data[label] = np.where(Master_Data["Genres"].str.contains(label),1,0)

In [43]:
Master_Data.shape

(1000209, 30)

In [44]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn import preprocessing
from sklearn.model_selection import cross_val_score

In [45]:
data_model = Master_Data.drop(["UserID","Zip-code","Timestamp","Title","Genres","Movie"],axis=1)

In [46]:
data_model.columns

Index(['Gender', 'Age', 'Occupation', 'MovieID', 'Rating', 'Movies', 'Drama',
       'Animation', 'Children's', 'Musical', 'Romance', 'Comedy', 'Action',
       'Adventure', 'Fantasy', 'Sci-Fi', 'War', 'Thriller', 'Crime', 'Mystery',
       'Western', 'Horror', 'Film-Noir', 'Documentary'],
      dtype='object')

In [47]:
data_model.head()

,Gender,Age,Occupation,MovieID,Rating,Movies,Drama,Animation,Children's,Musical,...,Fantasy,Sci-Fi,War,Thriller,Crime,Mystery,Western,Horror,Film-Noir,Documentary
0,F,1,10,1193,5,One Flew Over the Cuckoo's Nest,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,M,56,16,1193,5,One Flew Over the Cuckoo's Nest,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,M,25,12,1193,4,One Flew Over the Cuckoo's Nest,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,M,25,7,1193,4,One Flew Over the Cuckoo's Nest,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,M,50,1,1193,5,One Flew Over the Cuckoo's Nest,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [48]:
data_model["Gender"] = data_model["Gender"].map({"F":0,"M":1})